[package]
name = "pico-reverse-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "0.14"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }

